### ISSUE TITLE
W1KG22562 issues

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/archive-issues#10]
1) The list of page names added to the image group for W1KG22562 - I1KG22632 had a trailing newline which caused the pechaviewer to fail to display the final page and the PDF generation to also fail when including the final page. 

I have manually removed the trailing newline. The trailing newline was introduced when the sync script invoked the imagegroup-updater.xql. The imagegroup-updater.xql may be able to be modified to ensure that there is no trailing newline or other whitespace

2) image I1KG226320003.jpg shows as 30.94" x 6.68" while the remaining pages show as 4.46" x 0.96". Later image  I1KG226320205.jpg appears as 14.50" x 27.33". These problems need to be resolved and are likely owing to inconsistent dpi in the image metadata

**Comment by xristy** [comment]
The archive sync script, the imagegroups-updater.xql, and the app-server have been updated to ensure that there is no extraneous trailing (or leading) newlines or other whiitespace to confound the pechaveiwer

**Comment by TBRC-Travis** [comment]
#2 has been fixed.  Indeed, the issue was caused because of a discrepancy between the dpi listed in the metadata and the resolution of the image itself.  I cleaned up the metadata for the offending images and normalized the image size.  I reviewed the resulting PDF and it is much more pleasing to the eye now.  :)
