### ISSUE TITLE
W00KG03990: "archive" folder contains unorganized images

### ISSUE THREAD

**Issue by TBRC-Travis** [BuddhistDigitalResourceCenter/archive-issues#5]
in W00KG03990/archive there is an "uncropped" folder which contains unorganized source materials.  the image files in this folder need to be moved under each individual image group folder.  

@karmagongde - if you can look in the "uncropped" folder and tell me which images belong to which volume I can take care of moving the files.

**Comment by karmagongde** [comment]
Hi Travis,
I checked W00KG03990 in archive and the folder named
uncropped/KMP/W00KG03990 is empty. You said "uncropped" folder which
contains unorganized source materials. Where are those materials. I will
look those.

**Comment by TBRC-Travis** [comment]
Hi Karma,  I just renamed the folder a little bit to make it easier to see.  Please look in W00KG03990/archive/uncropped/KMP

**Comment by karmagongde** [comment]
Hi Travis, W00KG03990/archive/uncropped/KMP is empty. rest 6 folders looks
good. These are cropped from microfilm at India. image size and quality are
not great. So, please delete the "uncropped/KMP" folder. Thank you.

**Comment by TBRC-Travis** [comment]
Karma helped me clean up the folders in W00KG03990/archive.  It now contains just image group folders with the appropriate source materials.

**Comment by karmagongde** [comment]
Travis: I added first two pages in individual folder in archive of
W00KG03390. since this is archive and each images has 4 pages, we can't
rename as image folder. But we can just rename as general 0003 ...

Please let me know what needs to clean up in W00KG03990/archive.

**Comment by xristy** [comment]
I just looked in RS3://volume1/Archive/W00KG03990/archive at the first two image groups: W00KG03990-I00KG04020 and W00KG03990-I00KG04021.

They look fine to me. So I'm not clear what is meant by "**since this is archive and each images has 4 pages, we can't rename as image folder.**"

It looks like 6 volumes each named according to the scan request. Is that different from "rename as image folder"?

**Comment by karmagongde** [comment]
Images in image folder are cropped and named according to the image group
number. But in archive folder, the images are not cropped and there are 4
pages in each image.
For me too what is named in W00KG03990 looks fine.

**Comment by xristy** [comment]
Ah! Now I think I got it!

The image files in **W00KG03990/archive/W00KG03990-I00KG04020**, etc can not be renamed to be named like they are in **W00KG03990/images/W00KG03990-I00KG04020** because there are multiple pages in each file; however,

That is often the case I think since many materials are not organized neatly as single image per page when they arrive; further, 

It is **preferable to not rename** the image files in Wxxx/archive/Wxxx-yyy _in any case_ so that we retain the original naming in the case of a need to refer to it with the producer of the image file or for other audit purposes.

**Comment by TBRC-Travis** [comment]
Yes.  Thank you for your detailed attention to this work Karma.  I agree with what Chris said.  The state of the files as they are now in the archive folder is actually what's preferred and matches what exists in many of the archive folders throughout our library.  I think we can go ahead and close this now.
